version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    executor: node/default
    steps:
      - run: echo "beep"
  test:
    executor: node/default
    steps:
      - run: echo "beep"
  lint:
    executor: node/default
    steps:
      - run: echo "beep"
workflows:
  workflow:
    jobs:
      - build:
          name: My Build
      - lint
      - test:
          name: My Test
          requires:
            - My Build                                                                                                                                                                                       
